### ISSUE TITLE
Add a way to send a Redirect to client browser

### ISSUE THREAD

**Issue by andrea-magni** [andrea-magni/MARS#100]
Before latest refactorings, it was possible to access the underlying TWebResponse instance and send a redirect command to the client browser.
This is no longer accessible through IMARSResponse interface.
Please add a way to send the redirect command through IMARSResponse.

Thanks @acarlomagno for pointing this out.

**Comment by acarlomagno** [comment]
Good job! now it works better than before!

thanks @andrea-magni
