### ISSUE TITLE
Delphi 11, impossible to install

### ISSUE THREAD

**Issue by robnic69** [andrea-magni/MARS#107]
Just installed Delphi 11 trial. I have also downloaded the latest MARS.curiosity version. It's possible to build dpk but is not possible to install any. The INSTALL option is not present in the dpk's context menu.

**Comment by robnic69** [comment]
I see in demo apps that MARS components are created at runtime so probabliy what is written in the README file is wrong and there's no need to install packages.

1. Clone or download this project
1. Add folders to RAD Studio Library Path
1. Build All in the RAD Studio IDE
1. Install two packages <------

**Comment by masterinformaticaarezzo** [comment]
Nevermind, i see only now that there are two packages. One server and one client. The client has two packages that can be installed.
