### ISSUE TITLE
Issue with Unicode (Arabic characters)

### ISSUE THREAD

**Issue by gmurt** [andrea-magni/MARS#11]
Hi Andrea,

My REST server needs to be able to return Arabic text for some of my customers.  However, the only way I have been able to do this is to add in the following line to MARS.Core.Activation

```
        // 3 - fallback (raw)
        else
        begin
          Response.ContentType := TMediaType.CHARSET_UTF8_DEF;    // << inserted this line

          if (LMethodResult.Kind in [tkString, tkUString, tkChar, {$ifdef DelphiXE2_UP}tkWideChar,{$endif} tkLString, tkWString])  then
```
Without this, the unicode characters are not preserved when setting "Response.Content".

Can you confirm if this is a bug?  And/or if this is an acceptable fix.

Many thanks for your great work on this!

Kind regards,
Graham

**Comment by andrea-magni** [comment]
Hi Graham,
the fallback case you are listing is the last chance MARS has to provide a response in front of a method execution. It should be the last viable option that is to say you should not face this case often.

Would you please paste here the prototype of the method that is being called? 
And would you please tell me what are you reading (in debug) here:

```
          Response.ContentType := GetProducesValue;
          if Response.ContentType = '' then
            Response.ContentType := TMediaType.WILDCARD;
```

The Response.ContentType should be set via a "Produces" attribute on your method or should fallback to '*/*'.
Which deploy mode are you using? standalone application, service, apache module, isapi?

Thanks!

**Comment by gmurt** [comment]
Hi Andrea,

apologies for the delay.  I believe the issue can be seen when using your MARSHelloWorld demo.  I think it's related to the issue I am having also with the ignoring of Content Types.

Run the demo locally and using the Microsoft EDGE browser I hit F12 to analyse the traffic.  I then navigate to the following url...

http://localhost:8080/rest/default/helloworld/echostring/123

The Edge browser shows the response as having a content type of */*.  Even if I change the Produces() of the method to TEXT_HTML, it has no effect.

The edge browser simply tries to download the file instead of show the HMTL.

The following image should show the issue clearer...
https://www.dropbox.com/s/517q2r3ner9zdal/mars_screen.fw.png?dl=0

If there's anything else you need from me let me know.

Many thanks,
Graham :-)

**Comment by gmurt** [comment]
Hi Andrea,

I just did a GExperts search on your source code but I can't find a "GetProducesValue" method anywhere - maybe I've misunderstood what you were asking with the above code but I thought you wanted me to put a break-point on these lines to get the debug value.

```
Response.ContentType := GetProducesValue;    
```

**Comment by gmurt** [comment]
Ignore that last comment, it looks like I made a modification... let me investigate.

**Comment by gmurt** [comment]
Ah, ok I believe I have found the issue...  My method is returning a CHARSET_UTF8_DEF content type.

However, when the Content is written to the Response object in the following line the content type is TEXT/HTML

```
if (LMethodResult.Kind in [tkString, tkUString, tkChar, {$ifdef DelphiXE7_UP}tkWideChar,{$endif} tkLString, tkWString])  then
            Response.Content := LMethodResult.AsString
```

the "Response.ContentType := GetProducesValue;" line isn't called until further down which causes a problem as within the Web.HTTPApp unit at the following line...

`Bytes := EncodingGetBytes(ContentType, AValue);`

Because at the above call, the ContentType hasn't been set to our actual "Produces" value, the Unicode is not written correctly to the response object.

It may not be the correct way to do this, but It seems to be fixed by moving the following 2 lines to the top of the method...

```
begin
  Assert(Assigned(FMethod));

  // cache initial ContentType value to check later if it has been changed
  LContentType := Response.ContentType;

  Response.StatusCode := 200;    // moved these 2 lines from further down
  Response.ContentType := GetProducesValue;   // moved these 2 lines from further down
```

This way, at the point that we write the content to the HTTP Response object, the ContentType has already been set to what we require so that the correct encoding takes place.

I hope I've explained that correctly, if not let me know and I'll do my best to give more information.

Thanks,
Graham

**Comment by andrea-magni** [comment]
Hi Graham,
first of all, thanks for your effort :-)
I had a closer look this morning and these are mine conclusions:

1) if I run the HelloWorld demo on my Win10 machine (italian locale) I can see the echostring method returning a Content-Type "text/plain; charset=ISO-8859-1" that I suppose is something Indy is adding somewhere (<https://www.dropbox.com/s/8pg3me5yy9fgnkh/HelloWorld_arabic_1.png?dl=0>)

2) if you set the Produces attribute of the echostring method to "text/plain;charset=utf-8" (<https://www.dropbox.com/s/76nhad3dzsqlgfb/HelloWorld_arabic_2.png?dl=0>), I get the problem with encoding you pointed out (in Web.HttpApp) with Edge (and Chrome) showing question marks instead of arabic characters;

3) with your fix (setting earlier the content type with respect to assigning Content) everything works (<https://www.dropbox.com/s/79yalgc6ogilmwr/HelloWorld_arabic_3.png?dl=0>)

I see no issues in moving those two lines upward (and I did it locally). Would you like to open a pull request here on GitHub.com? Your contribution would be publicly set this way. Otherwise I may commit the change tagging you in the commit message.

Apart of this, I'd like to say a few words about the "raw fallback" serialization mechanism we are at: MARS should most of the time find a MessageBodyWriter (that can properly handle encoding and set Content-Type accordingly). The raw fallback should be a very last chance to provide some content to the client. I am open to suggestion on how improve the current implementation of this part of the library.

Thanks again and looking forward your pull request or your permission to commit myself the changes (with credits).

**Comment by gmurt** [comment]
Hi Andrea,


Thanks for your response,  sure feel free to make the change there.  I use GIT for my projects but I don't fully understand Pull Requests 😊I guess I should learn a bit more about it but there's just not enough hours in the day!


I've now fully migrated my Restaurant software across to your MARS library from RemObjects and I'm loving it!  It makes things so much easier for me to manage/maintain/fix my code.


Thanks again for your efforts with this!


Graham :-)



--
Kind regards,
Graham Murt
Kernow Software

--
Follow us on twitter for news, updates and special offers
https://twitter.com/kernowsoftware


________________________________

**Comment by andrea-magni** [comment]
OK, closed with commit 43a8707d35423c9e7017b82cc0a96e8fa7294cfb 
Thanks again and let me know if you found anything else.

**Comment by gmurt** [comment]
No problem Andrea!


One quick question, do you have any tips for getting compression to work with the REST library?


I can't seem to get it to work and I'm running out of ideas.  I've tried assigning an IndySSL component andplacing zlib.dll in the root folder but it doesn't appear to be compressing the output.


--
Kind regards,
Graham Murt
Kernow Software

--
Follow us on twitter for news, updates and special offers
https://twitter.com/kernowsoftware


________________________________

**Comment by andrea-magni** [comment]
Hi, it depends on what deployment strategy you are using. I tend to have an Apache instance in front of my MARS servers and let Apache do SSL and gzip where needed. 

However it should be easy to implement gzip compression inside MARS itself using an AfterInvoke hook (TMARSActivation.RegisterAfterInvoke). Maybe I will add a demo ASAP (though I feel comfortable with the Apache proxy). 

Have a nice day

**Comment by gmurt** [comment]
Hi Andrea,

Thanks for your reply. I don't actually  run a web server in front of my MARS server.

I run it on 2 AWS servers which are exposed to the internet via an AWS Load Balancer. The load balancer handles all of the ssl loading/unloading so my servers just sit on port http 8080 without needing to know anything about ssl.

Works really well and keeps my servers really simple (just the MARS server) but the load balancer doesn't handle compression so this is what I am trying to do.

I'll keep playing with it here to see if I can find a solution.

Thanks again!


Kind regards,

Graham Murt
Kernow Software Ltd
________________________________
