### ISSUE TITLE
Could not find an example to access database from FEngine.BeforeHandleRequest

### ISSUE THREAD

**Issue by ertankucukoglu** [andrea-magni/MARS#115]
Hello,

I would like to build remote IP based blocking system. Even this is not the main job of MARS, I am "kindly" asked to do it. I do not need any IPv6 functionality for my use case.

There will be a database with a table with one column blacklisted IP numbers and I need to block incoming request if any IP matches in any IP in that table.

Normally I can use `TMARSUniDAC` or `TMARSFireDAC` but I couldn't find a way to access them in subject mentioned method.

It would be more convenient for me to handle such checks in Server.Resource.pas file if that is possible. I already have all necessary database access built in there. Unfortunately, I couldn't add `IMARSRequest` in my method classes. I also don't know if latest codebase allows me to do that.

A simple example/description should be enough for me to keep going. If I can manage this, I am going to build a simple demo project to be added in sources.

Thanks & Regards,
Ertan

**Comment by andrea-magni** [comment]
Hi @ertankucukoglu ,
you can get a reference to `IMARSRequest ` easily, inside your resource definition:

```
  [Path('helloworld')]
  THelloWorldResource = class
  protected
    [Context] Request: IMARSRequest; // <<<<<<<<<<
  public
    [GET, Produces(TMediaType.TEXT_PLAIN)]
    function SayHelloWorld: string;
  end;
```
Just be sure to add `MARS.Core.RequestAndResponse.Interfaces` unit to your uses clause.
At this point it would be trivial to check the RemoteIP:

```
function IsAllowedIP(const AIP: string): Boolean;
begin
  Result := AIP.StartsWith('192.168.');
end;

{ THelloWorldResource }

function THelloWorldResource.SayHelloWorld: string;
begin
  if not IsAllowedIP(Request.RemoteIP) then
    raise EMARSHttpException.Create('Blacklisted IP', 401);

  Result := 'Hello World!' + sLineBreak + 'IP: ' + Request.RemoteIP;
end;
```

IsAllowedIP function is just an example, of course. You can lookup in a database (beware of performances!) before executing the request, just as I am doing in this example.

Nonetheless, it is not hard to implement the blocking mechanism to a higher level, using the RegisterBeforeInvoke method of TMARSActivation (check Server.Ignition.pas of MARSTemplate to have an idea). There you'll have the IMARSActivation (includes Request and Response and the AIsAllowed argument).
You can always manually create a TMARSFireDAC instance (providing the AActivation argument of course), just remember to free it when possible and/or add it to the activation's context.


Let me know if something is unclear.

Sincerely,
Andrea

PS: sorry for the late.

**Comment by ertankucukoglu** [comment]
Hello,

Having a refe3rence in my resource definition solved my problem.

Thanks.
