### ISSUE TITLE
GET method to upload a file

### ISSUE THREAD

**Issue by ertankucukoglu** [andrea-magni/MARS#121]
Hello,

There is this bulk json data that I would like to squeeze in a ZIP file for reducing internet transfer times.

I can prepare json, write it in a file, compress and make a ZIP file, but failed to upload that file in a GET method. What I am after is to send BYTE data to client.

Any help is appreciated.

Thanks & Regards,
Ertan

**Comment by bobprog72** [comment]
Hi Ertan,
look at ContentType demo.
There are "GetStream" and "GetStreamAsAttachment" functions.

Regards.
Bob

**Comment by ertankucukoglu** [comment]
That was it. I didn't try TStream obviously. And some headers of course.

Thanks for pointing me to right demo project and function(s) in it.
