### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by TeoWin** [andrea-magni/MARS#124]
[dcc32 Error] E2466 Never-build package 'MARSClient.FireDACDesign' requires always-build package 'MARSClient.CoreDesign'

**Comment by andrea-magni** [comment]
Hi, I saw your previous message about MARSClient.CoreDesign version but it seems already fine:

![image](https://user-images.githubusercontent.com/7839604/174283136-ac5d6b12-692c-475d-83ed-75d2b889a91a.png)

MARSClient.FireDACDesign requires MARSClient.CoreDesign so I guess your first issue with MARSClient.CoreDesign resulted this new issue you are having with MARSClient.FireDACDesign.

Please rebuild everything and see it if goes away.

Thanks for the feedback.
Sincerely,
Andrea

**Comment by TeoWin** [comment]
Hi Andrea,

Yes, I had some issues when I overlooked the MARSClient projectgroup so I guess you saw mutilple edits ;-)

Let me clarify: I am installing in 10.4 so package version 27. In 104Sydney the LIB Suffix is 26.

And when opening the Marsclient.groupproj groupproject, I can compile MARS.Utilis270, MARSClient.Core270, MARSClientCoreDesign270, MARSClient.FireDAC270 and MARSClient.FiredDACDesign270.
(in that order).

I can install the designtime package MARSClient.CoreDesign but not the MARSClient.FireDACDesign package. 
I normally respect package orders in a project group as if that is ment for that situation. 

You can install the package when build control is set to "Rebuild as Needed".

Best regards,
Teo

**Comment by andrea-magni** [comment]
Thanks for pointing this out, I just fixed the project files. Please reopen the issue if something still doesn't work.
