### ISSUE TITLE
const tkWideChar not exist in XE7

### ISSUE THREAD

**Issue by jairgza** [andrea-magni/MARS#14]
Can't compile Authorization demo in XE7,  in line  `{$ifdef DelphiXE6_UP}tkWideChar, {$endif}` the const tkWideChar not exist,   must be tkWChar i think

**Comment by bogdanpolak** [comment]
Probably there was the problem:

https://github.com/andrea-magni/MARS/blob/8ad4b364cb85def0d1acc07e73c6e1b5b3a63303/Source/MARS.Core.Utils.pas#L240

https://github.com/andrea-magni/MARS/blob/8ad4b364cb85def0d1acc07e73c6e1b5b3a63303/Source/MARS.Core.JSON.pas#L192

It looks that code is not consistent. 

What for is this code: 
```{$ifdef DelphiXE6_UP} tkWideChar, {$endif}``` ?

System type kind has following declaration:

```pascal
type
  TTypeKind = (tkUnknown, tkInteger, tkChar, tkEnumeration, tkFloat,
    tkString, tkSet, tkClass, tkMethod, tkWChar, tkLString, tkWString,
    tkVariant, tkArray, tkRecord, tkInterface, tkInt64, tkDynArray, tkUString,
    tkClassRef, tkPointer, tkProcedure {, tkMRecord});
```

There is no tkWideChar but tkWChar

**Comment by andrea-magni** [comment]
I need an XE7 to actually check. The DelphiXE7_UP conditional means "from XE7, included, and above versions" so I would expect both lines of code to not compile on XE7.
I don't have an XE7 VM at the moment, will check ASAP.
If someone with an XE7 machine can try to build MARS and fix this, would be very appreciated.

**Comment by andrea-magni** [comment]
Actually I am a bit puzzled about this and yes those two occurrences are not consistent.
tkWideChar is an alias for tkWChar (at least in Tokyo this is true) so probably we could use tkWChar everywhere...
