### ISSUE TITLE
Memory Leak found

### ISSUE THREAD

**Issue by bobprog72** [andrea-magni/MARS#144]
with a resource as in attached file, every get generate a memory leaks.
[Server.Resources.zip](https://github.com/andrea-magni/MARS/files/14434840/Server.Resources.zip)

**Comment by ertankucukoglu** [comment]
Hello,

You are using a `class` as a return value. If you can convert it to a
record (and your class structure seems convertible to a record) you would
be fine.

My knowledge is that only TFDQuery, TUniQuery are automatically freed.
Though, I am not an expert of the library. Maybe you need to set something
for MARS to free the class after it's done.

Roberto Sartori ***@***.***>, 28 Şub 2024 Çar, 16:48
tarihinde şunu yazdı:

**Comment by bobprog72** [comment]
My Error: 
I need to create a destructor for the TTestParams class that launch the destruction for all TNameValue object into Params.

MARS correctly free only the result object.

@ertankucukoglu : thank you but I need to use an object..
