### ISSUE TITLE
Lots of errors for Delphi XE

### ISSUE THREAD

**Issue by limelect** [andrea-magni/MARS#2]
Lots of errors for Delphi XE. Including the test

**Comment by andrea-magni** [comment]
Hi, I will try to have a run with Delphi XE and improve compatibility soon.
Can you list some errors here?

Thanks

**Comment by limelect** [comment]
MARS.Utils.Parameters.JSON line 47
[DCC Error] MARS.Utils.Parameters.JSON.pas(47): E2431 for-in statement cannot operate on collection type 'TJSONObject' because 'TJSONObject' does not contain a member for 'GetEnumerator', or it is inaccessible


MARS.Core.JSON;
line 290
this is what i did    Result := LValue.AsInt;   //Int64; other wise errror
 and then i gave up

**Comment by andrea-magni** [comment]
I've just squashed a couple of commits addressing backward compatibility with older Delphi versions (tested with Delphi XE and XE4).
I am actively developing the library using latest versions (10.1.2 Berlin) but I know backward compatibility is important for most of Delphi users. I would be very happy if you try again and provide me some feedback about your experience.

Thanks,
Andrea
