### ISSUE TITLE
ISAPI body parms are empty

### ISSUE THREAD

**Issue by littleearth** [andrea-magni/MARS#23]
ISAPI dll projects will not provide any data in body parameters; example below (and attached) will create 2 files in c:\windows\temp for an ISAPI project. Both should contain the same data, however body-param.txt will be empty. Compiling as a standalone EXE body param works fine.

> type
>   [Path('helloworld')]
>   THelloWorldResource = class
>   protected
>     [context]
>     Request: TWebRequest;
>   public
>     [GET, Produces(TMediaType.TEXT_PLAIN)]
>     function SayHelloWorld: string;
>     [POST]
>     procedure POST([BodyParam] body: string);
>   end;

> procedure THelloWorldResource.POST(body: string);
> var
>   LStringList: TStringList;
> begin
>   LStringList := TStringList.Create;
>   try
>     LStringList.Add(body); // Empty in ISAPI project
>     LStringList.SaveToFile(TPath.GetTempPath + 'body-param.txt');
>     LStringList.Clear;
>     LStringList.Add(Request.Content);
>     LStringList.SaveToFile(TPath.GetTempPath + 'body-content.txt');
>   finally
>     FreeAndNil(LStringList);
>   end;
> end;
> 

[Uploading ISAPITest.zip…]()

**Comment by andrea-magni** [comment]
Hi, thanks for the feedback. Would you please check if it due to this https://quality.embarcadero.com/browse/RSP-14674 ?
To fix it, try to apply the provided workaround, for example adding this line: 

  Request.ReadTotalContent;

as the first line of the TMARSActivation.Prepare method (MARS.Core.Activation.pas, line 480).
I don't have an IIS up and running right now to test it (I will later this week).

Thanks!

**Comment by littleearth** [comment]
That seems to fix it. Thanks!

**Comment by andrea-magni** [comment]
Great. Are you using Tokyo? The fix is marked as Fixed with Berlin 10.1 Update 1...

**Comment by littleearth** [comment]
Yeah, Tokyo. I have not applied 10.2.2 but I have another machine with that installed, I will test on that as well.

**Comment by littleearth** [comment]
Still an issue in 10.2.2

**Comment by andrea-magni** [comment]
I pushed the workaround and also commented on the JIRA issue in order to ask Embarcadero to fix it definitely.

Here is the commit: https://github.com/andrea-magni/MARS/commit/a7631a290cf610ba9543e523324bc0e3a065c38f

Thanks
