### ISSUE TITLE
can't compile MARS.DelphiRazor package in Delphi Berlin

### ISSUE THREAD

**Issue by jeanvdr** [andrea-magni/MARS#3]
after installing DelphiRazor package from Marco Cantu or yours, got the same fatal compile error: it is a DelphiRazor package error: can't find RlxRazor.pas, I think it is more RlxLocales.pas. It is in the source directory of DelphiRazor and it is added in the library directory.

**Comment by andrea-magni** [comment]
Hi, 
have you added the delphirazor\source folder to your library path? MARS.DelphiRazor package is a way to integrate the DelphiRazor in MARS, you have to download and install DelphiRazor before compiling it.
I've just tried and everything seems fine... 

Let me know, thanks!

Andrea

**Comment by jeanvdr** [comment]
Yes, DelphiRazor is installed and the source directory is added to the library path.
I have no problem compiling the MARS/Gallery demo which use DelphiRazor though. 
![image](https://cloud.githubusercontent.com/assets/26046164/23546577/86db5ca8-0000-11e7-8232-a0a1f2122fa9.png)
![image](https://cloud.githubusercontent.com/assets/26046164/23546609/b714e8da-0000-11e7-9ca2-6f0185ec2dc8.png)
![image](https://cloud.githubusercontent.com/assets/26046164/23546640/d9f4336a-0000-11e7-8a4a-f967659a8cdb.png)

**Comment by andrea-magni** [comment]
Have you added the library path for the specific platform you are compiling? (Sorry if it seems a super easy question, I can't think anything else at the moment...)

**Comment by jeanvdr** [comment]
Yes, I did. I've compiled a lot of packages in my live and this is very odd.

**Comment by andrea-magni** [comment]
Is it possible you have built the package with different Delphi versions installed on the same machine? I suggest you to perform an extended search (I use UltraSearch https://www.jam-software.com/ultrasearch/ ) to look if you have some other RazorPackage.bpl / .dcp and or RlxRazor.pas / .dcu or RlxLocales.pas / .dcu and clean them all.
Then try again to install DelphiRazor and compile the MARS package...

Let me know if you solve!

Thanks

**Comment by jeanvdr** [comment]
Did an Ultrasearch, no razor files hidden
I clearly miss something

**Comment by andrea-magni** [comment]
May I assume you solved this one? (If so, please write here what happened for future reference, thanks)

Thanks

**Comment by jeanvdr** [comment]
Not really...
The only way I can compile MARS.DelphiRazor is to remove the razor.dcp from the required packages and decline to import razor102.dcp as proposed when compiling, then I get only warnings but it compiles.
