### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by samuel-cruz** [andrea-magni/MARS#31]
Hello, I would like to know how to change the value of **JWT_SECRET_PARAM_DEFAULT** without having to directly change the value of the counter.

The way you are here:

_{TMARSToken}

constructor TMARSToken.Create (const AToken: string; const AParameters: TMARSParameters);
begin
   Create (
     AToken
   , AParameters.ByName (JWT_SECRET_PARAM, **JWT_SECRET_PARAM_DEFAULT**) .AsString
   , AParameters.ByName (JWT_ISSUER_PARAM, **JWT_ISSUER_PARAM_DEFAULT**) .AsString
   , AParameters.ByName (JWT_DURATION_PARAM, JWT_DURATION_PARAM_DEFAULT) .AsExtended
   );
end;_

I would like to change the JWT_SECRET_PARAM_DEFAULT and JWT_ISSUER_PARAM_DEFAULT values.

I tried inheriting from the TMARSToken class, but I could not get TMARSmORMotJWTToken.LoadJWTToken to use my key to validate authentication.

**Comment by andrea-magni** [comment]
Hi Samuel,
values can be set in application's parameters.
Have a look at the Server.Ignition.pas file and you can spot this line:
FEngine.Parameters.LoadFromIniFile;

You can specify an INI file name or, by default, it will look for an INI file with the same name of the executables. You can see an example file here:

https://github.com/andrea-magni/MARS/blob/master/Demos/TokenAutorenew/bin/TokenAutorenewServerApplication.ini

There is an entry to define the DefaultApp.JWT.Duration parameter where DefaultApp is the name of your app and JWT.Duration is the parameter name (here https://github.com/andrea-magni/MARS/blob/master/Source/MARS.Utils.JWT.pas you can find every JWT parameter's name).
You are going to change the JWT secret so just add this line:
DefaultApp.JWT.Secret=your_secret_here

If you don't want to have an INI file with parameters, you can set the same parameter directly in the Server.Ignition unit (right after or replacing the LoadFromIniFile call):
FEngine.Parameters.Values['JWT.Secret'] := 'your_secret_here';

No need to inherit TMARSToken or override methods. Just set the parameter and everything will run smooth. Let me know if you solve or if you find any other trouble.

**Comment by samuel-cruz** [comment]
Hi Andrea,

I made several attempts to use the .ini file and also changing the value of the parameter as indicated, but I realized that the key is being used only to generate the token, in the validation it does not read the parameter, it takes the default value.

I put a breakpoint in the MARS.Core.Token file, constructor TMARSToken.Create (AToken, ASecret, AIssuer: string; const ADuration: TDateTime); and forced the use of my key (ASecret), then yes it worked. Without that, it returns "Token missing, not valid or expired".

**Token Generation**
curl -X POST \
  http://localhost:211/api-scvisual/autenticacao/token \
  -H 'Postman-Token: ff238cda-7f61-461a-af80-a9372aa8210c' \
  -H 'cache-control: no-cache' \
  -d 'username=admin&password=10'

**Result**
{
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDE1MDg5NTgsImlhdCI6MTU0MTQyMjU1OCwiZHVyYXRpb24iOjEsImlzcyI6IlNDIFNvZnR3YXJlIChzY3Zpc3VhbCkifQ.jL5DjRwJFQ8WPiXkKmNRFE6GroplB-o1RoY_46Ek0oI",
    "IsVerified": true,
    "Expiration": "2018-11-06T10:55:58.000-02:00",
    "IssuedAt": "2018-11-05T10:55:58.000-02:00",
    "Claims": {
        "exp": 1541508958,
        "iat": 1541422558,
        "duration": 1,
        "iss": "SC Software (scvisual)"
    }
}

**Using the token**
curl -X DELETE \
  http://localhost:211/api-scvisual/v1/acabamentos/1 \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDE1MDg5NTgsImlhdCI6MTU0MTQyMjU1OCwiZHVyYXRpb24iOjEsImlzcyI6IlNDIFNvZnR3YXJlIChzY3Zpc3VhbCkifQ.jL5DjRwJFQ8WPiXkKmNRFE6GroplB-o1RoY_46Ek0oI' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: c96a9a9c-ed15-40e5-9133-10c6f83493bd' \
  -H 'cache-control: no-cache' \
  -H 'loja: 1C5DC12C-F492-4DDE-BFAE-AA4F32295FD4'

**Result**
Token missing, not valid or expired

Thanks!

**Comment by andrea-magni** [comment]
Hi, everything seems to work on my side...
Please put a breakpoint in TMARSToken.Load and check the ASecret value.
This is an example of the ini file you should set up:
[DefaultEngine]
DefaultApp.JWT.Secret=Andrea

Please double check if you have changed the name of the Engine (DefaultEngine) or of the application (DefaultApp).
Alternatively you can try to set the parameter via code:

    FEngine.Parameters.LoadFromIniFile;
    FEngine.Parameters.Values['DefaultApp.JWT.Secret'] := 'Test123';
    FEngine.AddApplication('DefaultApp', '/default', ['Server.*']);

Again, beware DefaultApp name is used in the parameter name...

Let me know if you find the issue.
Thanks

**Comment by samuel-cruz** [comment]
Hi Andrea,

I got it!
I was doing FEngine.Parameters.Values [JWT_SECRET_PARAM]: = 'MyKey';
Instead of doing FEngine.Parameters.Values ['MyApp.' + JWT_SECRET_PARAM]: = 'MyKey';

I will continue to study your framework so that I can learn more about it.

**Comment by andrea-magni** [comment]
Great to hear. You can try to use the ini file (more handy than having the secret compiled into the executable). I am going to close this issue, feel free to open other issues if you encounter troubles.
Sincerely
