### ISSUE TITLE
Discussion about README.md

### ISSUE THREAD

**Issue by bogdanpolak** [andrea-magni/MARS#33]
1) There are two copies of the README.md - should be synchronized
  - https://github.com/andrea-magni/MARS/blob/master/README.md
  - https://github.com/andrea-magni/MARS/blob/master/docs/README.md
2) Map of the functionalities and concepts is totally unreadable - especially in the PNG format, but with PDF is still difficult to read, you have to zoom in a lot. Maybe change it into the hierarchical list will be better
3) MARS image is beautiful, but it uses so much place important for ket message. Maybe you can consider to move it to the bottom of the file
4) In the JavaScript libraries are important source code examples in the README file. Something like that:
```pascal
type
  [Path('helloworld')]
  TSampleResource = class
  public
    [GET, Produces(TMediaType.TEXT_PLAIN)]
    function SayHelloWorld: string;
  end;

function TSampleResource.SayHelloWorld: string;
begin
  Result := 'Hello World!';
end;

procedure TForm1.Button1Click(Sender: TObject);
begin
  TMARSResourceRegistry.Instance.RegisterResource<TSampleResource>;
  FEngine := TMARSEngine.Create;
  FEngine.BasePath := '/rest';
  FEngine.Port := 8080;
  FEngine.AddApplication('DefaultApp', '/default', ['ServerResources. TSampleResource']);
  FServer := TMARShttpServerIndy.Create(FEngine);
  FServer.Active := True;
end;

procedure TForm1.FormClose(Sender: TObject; var Action: TCloseAction);
begin
  if Assigned(FServer) then
  begin
    FServer.Active := False;
    FreeAndNil(FServer);
    FreeAndNil(FEngine);
  end;
end;

```

**Comment by bogdanpolak** [comment]
Intresting README to go follow is 
https://github.com/spinettaro/delphi-event-bus/blob/master/README.md

* small logo
* not to many folders and files in the repo root directory allows to catch README content quickly 
* [Show me the code] section - coders like it a lot
* Diagram describing architecture

**Comment by andrea-magni** [comment]
Hi, I agree on most of your points.
Please go ahead and change the logo image with this one : /media/MARS_logo_256.png that will be much smaller.
I like your helloworld example: it is very minimalistic! But I would switch to console application (even more minimalistic!).
Feel free to move the functionalities map (out of date, though) to the bottom part (or simply link the PDF somewhere).

I really appreciate your effort to improve MARS overall first-impact effect ;-)

**Comment by bogdanpolak** [comment]
OK then ... let's switch this discussion in to two steps steps and close this discussion
1) General clean-up in the README (faster to implement)
2) Adding new sample there (discussion is needed during)

I can submit new Issues if it's OK for you ...
If you do not have anything to add to this topic then it can be closed

* First-impact effect is very important from my point of view. It is less technical thing, but very important, not only for number of stars, but also for popularity of the project

**Comment by andrea-magni** [comment]
OK, go ahead.
Thanks
