### ISSUE TITLE
More detailed exception message is required

### ISSUE THREAD

**Issue by bogdanpolak** [andrea-magni/MARS#34]
If you remove `MARS.mORMotJWT.Token` from uses section then REST server returning the exception: 
```
Internal server error: [EMARSException] Token injection failed in MARSActivation
```
No guidance what to do. Something like:
> Please add MARS.mORMotJWT.Token unit to uses section

**Comment by andrea-magni** [comment]
I agree, nice spot.
However I can anticipate, as soon as possible (that is when 10.3 Rio is available and mORMotJWT will be able to compile for Linux [ARC was an issue but now ARC is going away]), I plan to drop the JOSE JWT library in favor of the mORMotJWT library that is far more fast/reliable/independent library!
