### ISSUE TITLE
Resource Not Found handling

### ISSUE THREAD

**Issue by bogdanpolak** [andrea-magni/MARS#35]
https://github.com/andrea-magni/MARS/blob/0a508b0308f6a3db112691c2065536ae389c3c27/Source/MARS.Core.Engine.pas#L208-L217

When server do not find resource then it throwing the exception (as shown above) ...  why? Generally REST Servers are only responding with
```http
HTTP 404 Not found
Content-Type: application/json; charset=UTF-8

{"status":"error", "message": "Unsuported resource. Service denied to respond."}
```
or something similar

What is the difference? When you are using some Web Browsers to test MARS Server (I check just Chrome) they are asking for `favicon.ico` and when server is run with the debugger mode you will receive this exception in the IDE - it looks that something is wrong but it isn't (bad perception)

**Comment by andrea-magni** [comment]
In the latest MARSTemplate version, you can spot a region with a OnBeforeHandleRequest implementation example specifically written to avoid the favicon.ico request.
Look for this {$REGION 'OnBeforeHandleRequest example'} in the Server.Ignition.pas file

**Comment by bogdanpolak** [comment]
If you confirm that is OK for you then I will try to add to to IDE Wizard template too. Can I go with that?

**Comment by andrea-magni** [comment]
Yes thanks. The IDE wizard actually needs some love as at some point I preferred the MARSCmd approach.
I lack knowledge to make the IDE wizard fair enough. So, yes, if you are capable go ahead, thanks!

**Comment by bogdanpolak** [comment]
@andrea-magni then let’s go with that.

I like new labels a lot. I’m crazy about them. You can add also [new feature] to this task

**Comment by bogdanpolak** [comment]
@andrea-magni ... you can close this Issue :-) I'm going to register new Issue for improving IDE Wizard, because of the title. I'm also not a master on the RAD Studio Open API, but can dig more. 
Maybe someone else in the meantime will catch this task.
