### ISSUE TITLE
MARS Pascal Style Guide is mandatory

### ISSUE THREAD

**Issue by bogdanpolak** [andrea-magni/MARS#36]
To not speed (in the future) a lot of time for unproductive discussions we have to define this repo Style Guide. At the beginning we can start with formatting in the uses section (which is now important) and improve other sections in the future.

**Comment by bogdanpolak** [comment]
Some arguments for this Style Guide:
https://google.github.io/styleguide/cppguide.html#Goals

**Comment by andrea-magni** [comment]
I tend (in all my projects) to follow this convention:
uses
  <Delphi RTL units>,
  <Standard libraries (i.e. FireDAC) units>
  <Current framework (i.e. MARS) units>
  <Application units>
;

In some situations where this makes sense I tend to separate even units in the same "group", according to some specific characteristic: i.e. all FB related units of FireDAC all on the same line...

**Comment by bogdanpolak** [comment]
It look difficult to follow if those rules are not described precisely. For that moment can we start StyleGuide.md with only **Uses** section and describe it.
What about code formatting?

**Comment by andrea-magni** [comment]
I am not a huge fan of code formatters as, even if I try to stay consistent, sometimes I want to keep a custom formatting to improve readability...
But I totally agree I can describe my style in the Style Guide. 
Thanks for pointing this out!

**Comment by baka0815** [comment]
``clang-format`` does support a wide variety of formatting but I don't now if it's useful for Pascal code.

**Comment by bogdanpolak** [comment]
@baka0815 I’m afraid that it could be too little powerful. Even pure Object Pascal formaters can’t manage with new Delphi syntax like anonymous methods and generic types, but it’s good to know about such tool, thanks

**Comment by bogdanpolak** [comment]
@andrea-magni OK then no code formatters with MARS. My heart is crying, but let it be. 

By the way ... Maybe that should be mention in the Style Guide that code has too be formatted manually according to the rules
