### ISSUE TITLE
can't compile packages in /MARS/Packages/10Seattle folder

### ISSUE THREAD

**Issue by ErwinMouthaan** [andrea-magni/MARS#4]
The MARS / Packages / 10Seattle folder contains MARSClient.dpk and MARSServer.dpk. Compiler errors with Delphi 10 Seattle.

I have changed search path ..\..\Source\Core in ..\..\Source
I also removed MARS.Core.Request.pas from MARSServer package.
Still compiler errors.

**Comment by andrea-magni** [comment]
Hi @ErwinMouthaan , thanks to @davidesfn, you may want to try again and see if everything works now.
Let us know!

**Comment by ErwinMouthaan** [comment]
It compiles! Great!
In demos projects search path has to be changed though. Minor issues of course.
Thanks again!
