### ISSUE TITLE
[Internal] Short commit names

### ISSUE THREAD

**Issue by bogdanpolak** [andrea-magni/MARS#41]
@andrea-magni ... you should give short names for your commits - this is well known good practice - especially useful when you working in the bash terminal or the windows cmd. See good articles about this:

* https://chris.beams.io/posts/git-commit/
* https://github.com/erlang/otp/wiki/writing-good-commit-messages

When you have to add more info to commit description just add short title in the 1 line then empty line and then full description, something like that (it is form your last commit):

```text
Added raise an exception when none Message Body Writer is selected

regression: 
    given I removed the primitive types fallback in favor of a more uniform MBW implementation (see commit e90626798fc9bd430868743264cd30c7c64b529d), no content serialization happens when no MBW matches the request (i.e. no MBW are registered in the system). This leads to situation like the one described in #40.
    With the current commit, I am raising an exception if the invoked REST method is actually a function and no MBW are selected for response serialization.
```

**Comment by andrea-magni** [comment]
Thanks for pointing this out. I generally work with TortoiseGit and multi-line commit messages are not an issue there...
