### ISSUE TITLE
EKON 22 Demo sending TMyRecord via CURL

### ISSUE THREAD

**Issue by bogdanpolak** [andrea-magni/MARS#42]
I was testing a new EKON 22 demo and found small issue. I'm sending:
```
curl -X POST -H "Content-Type: application/json" -d "{'Firstname':'Bogdan','Lastname':'Polak','DateOfBirth':'2001-01-10'}" -v "http://localhost:8080/rest/default/helloworld/recordAge"
```
and response is
```
< HTTP/1.1 200 OK
< Connection: close
< Content-Type: application/json
< Content-Length: 107
< Date: Mon, 12 Nov 2018 19:49:39 GMT
<
{"Name":" ","Seconds":-543749917,"Minutes":62520289,"Hours":1042004,"Days":43416,"Months":1426,"Years":118}* Closing connection 0
```

118 years is quite a lot. :-) I checked that is since data zero, means 1899-12-30. Is there something wrong or I was missing something?

I was trying different date formats: `2001-01-10T00:00:00.000+02:00`, `2001-01-10T00:00:00`, `2001-01-10Z00:00:00` but the response is still the same

**Comment by andrea-magni** [comment]
I would say curl is messing up something with the JSON in the body. The response you get is actually an empty response (you can see Name is empty as well).
I managed to get it to work escaping double quotes:
```
curl -X POST -H "Content-Type: application/json" -d "{\"Firstname\":\"Bogdan\",\"Lastname\":\"Polak\",\"DateOfBirth\":\"2001-01-10\"}" -v "http://localhost:8080/rest/default/helloworld/recordAge"
```
I am using Linux Bash Shell on my Win10 development machine.
