### ISSUE TITLE
Please make proxy settings accessible in TMARSClient (non component based approach)

### ISSUE THREAD

**Issue by Davide675** [andrea-magni/MARS#47]

**Comment by andrea-magni** [comment]
Please @Davide675  make some test, if you can. I don't have a proxy available at the moment (will try soon).

**Comment by Davide675** [comment]
Ty it's working as a charm

Example:
`  TMARSNetClient.RegisterBeforeExecute(
    procedure (const AURL: string; const AClient: TMARSCustomClient)
    begin
      (AClient as TMARSNetClient).HttpClient.ProxySettings := TProxySettings.Create('proxyname',
                                                                                    proxyport, 'username', 'password', 'http');
    end);
  ShowMessage(TMARSNetClient.GetJSON<TJSONValue>('http://myproxy:port/bin', 'server', 'heartbeat').ToString);
`

**Comment by andrea-magni** [comment]
Great, thanks!
