### ISSUE TITLE
Issue with returning a TJsonObject

### ISSUE THREAD

**Issue by gmurt** [andrea-magni/MARS#51]
I'm getting an the following error when trying to call a resource which returns a TJsonObject with the latest MARS repo.  The error is 

Project JsonDataObjectsVCL.exe raised exception class EMARSHttpException with message 'MessageBodyWriter not found for method HelloWorld of resource THelloWorldResource'.

This occurs with the MARS JsonDataObjects demo server under 10.3.  

**To Reproduce**
1. Run the JsonDataObjects server
2. Open a broser and navigate to "http://localhost:8080/rest/default/helloworld"

Configuration -
 - OS: Windows 10
 - Client: Chrome browser
 - Version Delphi 10.3

**Comment by gmurt** [comment]
Thanks Andrea and sorry for the delay.

I will test again today and let you know how it goes.

**Comment by andrea-magni** [comment]
Any news about this issue, @gmurt ?

Thanks

**Comment by gmurt** [comment]
Hi Andrea,

Apologies, I can’t remember if this was sorted or not... I’m currently skiing in the Austrian alps but will look as soon as I’m back on Monday.

Kind regards,

Graham Murt
www.kernow-software.co.uk

________________________________

**Comment by andrea-magni** [comment]
Don't worry @gmurt and happy skiing ;-)
Best regards, Andrea

**Comment by gmurt** [comment]
Hi Andrea,  

I think there may be a bug with the MARS.JsonDataObjects.ReadersAndWriters where it doesn't use a "fallback" encoding.

I've modified the source to resemble the standard JSON fallback mechanism as in the "procedure TJSONValueWriter.WriteTo" method.

My changed code looks like this and now appears to work without giving an Access Violation.  Can you check if this was a bug and if this is a suitable fix?


```
procedure TJsonDataObjectsWriter.WriteTo(const AValue: TValue; const AMediaType: TMediaType;
  AOutputStream: TStream; const AActivation: IMARSActivation);
var
  LJsonBO: TJsonBaseObject;
  LEncoding: TEncoding;
begin
  if not GetDesiredEncoding(AActivation, LEncoding) then
    LEncoding := TEncoding.UTF8; // UTF8 by default
```
