### ISSUE TITLE
Methods from child classes are not registered

### ISSUE THREAD

**Issue by norgepaul** [andrea-magni/MARS#62]
It appears that Mars only registers REST methods in the registered class, not the ones that appear in parent classes.

This code works:

```
  [Produces(TMediaType.APPLICATION_JSON)]
  [Path('test')]
  TTest= class
  protected
    function DoDefault: String; virtual;
  public
    [GET]
    function Default: String;
  end;

...

  function TTest.DoDefault: String;
  begin
    Result := 'Works!';
  end;

  function TTest.Default: String;
  begin
    Result := DoDefault;
  end;
...

  initialization
    TMARSResourceRegistry.Instance.RegisterResource<TTest>;  
```

This code returns no GET handler:

```
  [Produces(TMediaType.APPLICATION_JSON)]
  [Path('test')]
  TTest= class
  protected
    function DoDefault: String; virtual;
  public
    [GET]
    function Default: String;
  end;

  TTestChild= class
  protected
    function DoDefault: String; override;
  end;

  function TTest.Default: String;
  begin
    Result := DoDefault;
  end;

...

  function TTestChild.DoDefault: String;
  begin
    Result := 'Doesn''t Work!';
  end;

...

  initialization
    TMARSResourceRegistry.Instance.RegisterResource<TTestChild>;  
```

Is it possible to register with Mars attributes in parent classes?

**Comment by andrea-magni** [comment]
Hi @norgepaul ,
sorry for the late.
In the code you pasted here TTestChild is not an actual inherited class of TTest:
```
  TTestChild= class    // <--- (TTest) is missing?
  protected
    function DoDefault: String; override;
  end;
```

In MARS there are a couple of example of inherited classes exposed through the REST interface. Just have a look at each TTokenResource that is included in new projects created by MARSCmd utility. Or just have a look at the MARSTemplate demo where you can find it.

Please let me know if you solved and now everything is OK.
Best regards,
Andrea
