### ISSUE TITLE
GetDesiredEncoding(AActivation) - Not enough parameters

### ISSUE THREAD

**Issue by fiazhnd** [andrea-magni/MARS#64]
Hi Andrea Magni,

I am try to build your demo in RAD Studio 10.2 but following error after successfully install your component.

[dcc32 Error] MARS.JsonDataObjects.ReadersAndWriters.pas(56): E2035 Not enough actual parameters
[dcc32 Fatal Error] Server.Resources.pas(20): F2063 Could not compile used unit 'MARS.JsonDataObjects.ReadersAndWriters.pas'

Error appear in MARS.JsonDataObjects.ReadersAndWriters.pas unit as appears above as well, kindly fix it.

Best Regards
Fiaz

**Comment by andrea-magni** [comment]
It turned out I already fixed this in the develop branch. I've just backported the fix to master as well.
Now it should compile and work as expected.
Thanks!

Sincerely,
Andrea
