### ISSUE TITLE
MARS runs like a linux apache module

### ISSUE THREAD

**Issue by acarlomagno** [andrea-magni/MARS#67]
Hi,
I installed MARS on linux UBUNTU 18.04 server like a module and works fine with "Hello World" sample

I tried to access a MySQL database but I received a "internal server error" without explain

I tried like a console application and works fine ... I can read the database and display the data

One problem maybe is the .ini file
in the console mode I put the file into same folder of application and ok.

in module mode, I tried to put the file into module folder but I think is wrong

Someone tried this scenario?

thanks!
Antonello

**Comment by andrea-magni** [comment]
There was a bug determining the default configuration file name when MARS server is deployed as Apache module.
Now I'm using GetModuleName(hInstance) that should fit all cases.

Thanks for pointing this out.
