### ISSUE TITLE
Rest.Json

### ISSUE THREAD

**Issue by ettiennedup** [andrea-magni/MARS#72]
Hi I get rest.json dcu not found when  building. Is this because i am using Delphi EX2

regards
ettienne

**Comment by andrea-magni** [comment]
Hi @ettiennedup , I currently have no more VMs with XE2 so I can't test myself... sorry.
What is the name of the package you are compiling and fails?

Sincerely,
Andrea

**Comment by bogdanpolak** [comment]
@andrea-magni: As I wrote this in #76 I think you should limit MARS support to Delphi versions: **XE7 - 10.3 Rio**

@ettiennedup: I'm sorry, but I personally don't think that the older versions support (without the strong contribution of someone who uses XE2) is even possible.
