### ISSUE TITLE
THTTP.Net Client Async Crashes on Android and Delphi RIO 10.3.1

### ISSUE THREAD

**Issue by littleearth** [andrea-magni/MARS#73]
This is posted to help anyone else they might stumble across the issue so they don't waste hours like I did. The issue is not with MARS but effects MARS using HTTP.NET on Android and Delphi 10.3.1

Your application will crash randomly with Seg Faults, Bus errors.

TNetHttpClient can't work in multithread under android (RSP-23742)
[https://quality.embarcadero.com/browse/RSP-23742](https://quality.embarcadero.com/browse/RSP-23742)

Patch System.Net.HttpClient.pas with 

```
THTTPClientExt = record
--
case Integer of
0: (
FPreemptiveAuthentication: Boolean;
FSecureFailureReasons: THTTPSecureFailureReasons;
FAutomaticDecompression: THTTPCompressionMethods
);
1: (
_pad: array[0 .. 7] of Byte
);
end;

```

**Comment by andrea-magni** [comment]
Hi, thanks for pointing this out here.
Thankfully, Dmitry Arefiev already fixed the issue so we'll get this fixed in one of the future Delphi releases.

Sincerely

**Comment by bogdanpolak** [comment]
@andrea-magni: From MARS perspective you should close this issue - maybe adding label `out-of-scope`
