### ISSUE TITLE
Packages/101Berlin/MARSClient.CoreDesign.dproj has incorrect dcu output folder

### ISSUE THREAD

**Issue by fschetterer** [andrea-magni/MARS#74]
Package outputs to Lib250 instead of Lib240.
Simple Patch:
```
diff -r Packages/101Berlin/MARSClient.CoreDesign.dproj: bd3a5102 Packages/101Berlin/MARSClient.CoreDesign.dproj: Working Tree
51c51
<         <DCC_DcuOutput>..\..\Lib250\$(Platform)\$(Config)</DCC_DcuOutput>
---
>         <DCC_DcuOutput>..\..\Lib240\$(Platform)\$(Config)</DCC_DcuOutput>
```

**Comment by andrea-magni** [comment]
Thanks, I'll check but I have to get back my 10.1 Berlin VM.
What about submitting a pull request?

Sincerely,
Andrea

**Comment by fschetterer** [comment]
I'm just evaluating MARS, figured either run the patch or open the file in a text editor would be far the easiest. 
Forking, editing and submiting a PR seems overkill for one number :)

**Comment by andrea-magni** [comment]
OK, I've manually edited package files for Berlin (won't have a Berlin installation available before a few days). Please check if everything is fine now (daef64912b04036917cb336c4eee34438fa993a8)

Thanks
