### ISSUE TITLE
Missing conditional defines?

### ISSUE THREAD

**Issue by gmurt** [andrea-magni/MARS#8]
Hi Andrea,

There appear to be 2 references to TJsonBool in MARS.Core.JSON which are not wrapped in a   {$ifdef Delphi10Seattle_UP}

This prevents compiling in XE8 (and I assume earlier versions)

I've added the missing defines and will test here.

Kind regards,
Graham

**Comment by andrea-magni** [comment]
I am sorry I physically can't test everything on every Delphi release (I admit I usually code in the latest version, aka Tokyo today) and you are very welcome to submit a pull request whenever you find some backward compatibility issue.

Thanks! :-)

**Comment by gmurt** [comment]
Hi Andrea,

No problem, I have versions from XE8 installed here so will test the best I can.

I use Git for my project but don't fully understand fetch/pull differences... need to read more on this I guess.

P.s. Converted 2 of my apps now to use your mars library... was using remobjects before. I love your work!

Do you have a donation page/link where I can provide some funding for coffee/beer?

Kind regards,

Graham Murt
Kernow Software Ltd
________________________________

**Comment by andrea-magni** [comment]
Thanks for the kind words, Graham.
Once you have changes, you may want to fork this repository, commit them, create a pull request and I will merge them to the master repository (this one). This will also make up show up in the contributors page of this project.

I don't have a donation page but thanks for asking. The best thing you can do to support this project today is to spread the word ;-)

Thanks

**Comment by ErwinMouthaan** [comment]
In Delphi XE7 also TJSONBool is not defined in System.JSON. Any reference to TJSONBool in MARS.Core.JSON will therefor not compile.

In Mars.Core.Utils there is a `function BooleanToTJSON(AValue: Boolean): TJSONValue` defined. I guess this function can be used in MARS.Core.Utils to circumvent the problem TJSONBool type is not available in all Delphi versions.

**Comment by andrea-magni** [comment]
Hi, sorry for the late, I just pushed a commit for backward compatibility against XE4 ( <https://github.com/andrea-magni/MARS/commit/209ab10d516f2280fff1b506f96138f199853cab> ).
Now everything compiles (with XE4). Please reopen this issue if you face any glitches.

Thanks
