### ISSUE TITLE
Wrong response encoding name on UTF-8 systems

### ISSUE THREAD

**Issue by grzegorzdeyk** [andrea-magni/MARS#80]
Hi Andrea,
I've found a problem with handling national characters on systems where active encoding is set to one of Unicode or UTF-7 or UTF-8. It is because content-encoding in response header is set to "Default" instead of real name of encoding.

1. Prepare REST server using MARS HelloWorld demo with modifications to run it in console mode
2. Deploy it to Ubuntu Linux machine or Linux docker (e.g. PAServer docker) and run
2. Make this request _<host:port>/rest/default/helloworld/echostring/zażółć_ from browser on MS Windows machine
3. See that response text doesn't look like requested string. You may check Content-encoding is set to "Default" indead of "UTF8".

In my opinion there is no point of setting encoding name to "Default" in any scenario.

**My scenario:**
 - OS: server: Linux Ubuntu,  client: Windows 10 64bit
 - Client: Browser Edge 79.0.309.71

I've found that problem is in GetEncodingName function located in MARS.Core.Utils unit. In my opinion line
`  else if AEncoding = TEncoding.Default then Result :='Default'` 
should be at the end of if block. So finally GetEncodingName function should look like this: 
```
function GetEncodingName(const AEncoding: TEncoding): string;
begin
  Result := '';

  if AEncoding = TEncoding.ANSI then Result := 'ANSI'
  else if AEncoding = TEncoding.ASCII then Result := 'ASCII'
  else if AEncoding = TEncoding.BigEndianUnicode then Result :='BigEndianUnicode'
  else if AEncoding = TEncoding.Unicode then Result :='Unicode'
  else if AEncoding = TEncoding.UTF7 then Result :='UTF7'
  else if AEncoding = TEncoding.UTF8 then Result :='UTF8'
  else if AEncoding = TEncoding.Default then Result :='Default';
end;
```

Kind regards,
Grzegorz

**Comment by bogdanpolak** [comment]
@grzegorzdeyk: Can you check you MARS version and pull current master branch?
In the current MARS release function `GetEncodingName` is in a the unit: `MARS.Core.MessageBodyWriter.pas`.

@andrea-magni: If you are too busy. I can revert this order and request PR. I agree with Grzegorz that we should check all Web encodings first and apply Default as last one. If you are fine with that, please assign me, tag issue with bug label and add it into the 1.4 release (if you like)

**Comment by grzegorzdeyk** [comment]
You're right @bogdanpolak , `GetEncodingName` is in a `MARS.Core.MessageBodyWriter.pas`, but function body is still the same. :)

**Comment by andrea-magni** [comment]
Thanks a lot, I've just included the change in the develop branch
