### ISSUE TITLE
Range check error on POST request on Linux

### ISSUE THREAD

**Issue by BlackLanzer** [andrea-magni/MARS#81]
**Describe the bug**
If you send an array in POST on Linux the server crash with **Range check error** on this line https://github.com/andrea-magni/MARS/blob/master/Source/MARS.Rtti.Utils.pas#L255.  
On Windows it works fine.

**To Reproduce**
1. Send an array in POST

**Expected behavior**
The program should not crash

**Scenario (please complete the following information):**
 - OS: Linux

**Comment by meg02in** [comment]
I have the same problem in my project. I fixed the issue modifing the procedure in that way:

`//procedure SetArrayLength(var AArray: TValue; const AArrayType: TRttiType; const ANewSize: Integer);
procedure SetArrayLength(var AArray: TValue; const AArrayType: TRttiType; const ANewSize: PNativeInt);﻿
begin
  if AArrayType is TRttiArrayType then
  begin
    raise Exception.Create('Not yet implemented: SetArrayLength TRttiArrayType');
    { TODO -oAndrea : probably not needed }
  end
  else if AArrayType is TRttiDynamicArrayType then
    //DynArraySetLength(PPointer(AArray.GetReferenceToRawData)^, AArrayType.Handle, 1, @ANewSize);
    DynArraySetLength(PPointer(AArray.GetReferenceToRawData)^, AArrayType.Handle, 1, ANewSize);
end;`

and the changing accordly the unit MARS.Core.JSON.pas and MAR﻿S.Core.M﻿essageBodyReaders.﻿pas.

After that my project working good both under linux and under wndows in all kind of deploying method for the server tha MARS support.

I  attac﻿hed my sourc﻿e of MARS.Rtti.Utils, MARS.Core.JSON.pas e 
[RangeCheckFixing.zip](https://github.com/andrea-magni/MARS/files/4502236/RangeCheckFixing.zip)

MARS.Core.MessageBodyReaders.pas

**Comment by BlackLanzer** [comment]
Nice find @meg02in, but your fix has another bug.

In **MARS.Core.MessageBodyReaders.pas** and **MARS.Core.JSON.pas** you define the variable L for the new size of the array as an Integer.  
Later **DynArraySetLength** take a pointer to NativeInt. In my tests this caused a wrong read of the pointer value. I think it's because of 64 or 32 bit stuff.

I fixed it defining L as **NativeInt** and now it's working correctly on both Windows and Linux.

I can make a pull request later if everything is good.

**Comment by meg02in** [comment]
Hi,
thanks for your suggestion, i made your correction and tested for 1 week in a server of one of my customer.

All gone right

**Comment by andrea-magni** [comment]
Hi @meg02in  and @BlackLanzer , please go ahead and submit your PR! Thanks!
Please beware I have updated a bit the develop branch today so you may want to make a Pull before proceeding.

Waiting for your PR :-)

**Comment by andrea-magni** [comment]
For your convenience, I've just merged your corrections in the attached source files.
Please check everything is as you like and submit your PR, I will be happy to accept it.
If you could just rename that L variable to something like LNewLength I would appreciated it.

Thanks again :-)

[Source.zip](https://github.com/andrea-magni/MARS/files/4611163/Source.zip)

**Comment by andrea-magni** [comment]
This issue has been fixed thanks to the pull request #83
Many thanks for your contribution! :-)
