### ISSUE TITLE
Could you add an overloaded function to IMARSRequest?

### ISSUE THREAD

**Issue by gmurt** [andrea-magni/MARS#85]
Hi Andrea,

In my project I used the following which is not compatible with the latest version.

`[Context] Request: THttpRequest;`

I've changed to use the new interface version but it seems I'm missing the "request.QueryFields.Value[]" property which I used previously. 

I've made a modification to the interface to allow me to access query values by name...

```
    function GetFormParamValue(const AIndex: Integer): string; overload;
    function GetFormParamValue(const AName: string): string; overload;  <-- NEW 

....

function TMARSWebRequest.GetQueryParamValue(const AName: string): string;
begin
  Result := FWebRequest.QueryFields.Values[AName];
end;
```

Is there any chance you can include this in the next update?  

Many thanks,
Graham

**Comment by andrea-magni** [comment]
I just pushed some changes to add the GetQueryParamValue method overload that I think you were referring to. Let me know if everything is fine and feel free to reopen this issue if needed.
